### ISSUE TITLE
Invalid Patient Credentials: Authorization Code

### ISSUE THREAD

**Issue by duplexraid** [virencehealth/apiserver.virencehealth.com#97] opened 2020-01-15 10:44 UTC
Hi,

I am unable to receive an authorization_code, because the provided patient credentials do not work. 

User Name: Walter.caldwell@outlook.com
Password: TestPatient!@

Thanks!

**Comment by KedarGanta** [comment] 2020-01-23 22:24
@duplexraid  we have a setup issue with our public sandbox. The team will try to fix this issue.

**Comment by KedarGanta** [comment] 2020-01-23 23:47
@duplexraid  Please use these credentials 
User Name: Walter.caldwell@outlook.com
Password: TestPatient!@!

**Comment by duplexraid** [comment] 2020-01-29 09:17
Hi Kedar,

Thank you for your support. The credentials are correct, but outlook is requesting another verification step.

![image](https://user-images.githubusercontent.com/59915940/73343230-0983f700-42a2-11ea-8ae3-0948ccefa98f.png)

**Comment by nkadmane** [comment] 2020-04-09 05:12
@duplexraid 

Please try using these Credentials:

**User Name: athenainterop@aol.com
Password: Virence@123**

When it asks for second authentication please use the same credentials to login to AOL email account and  get the code.

**Comment by KedarGanta** [comment] 2020-05-29 23:33
@duplexraid  I would assume that the issue is resolved.. Hence closing the issue.

**Closed by KedarGanta** 2020-05-29 23:33 UTC
