### ISSUE TITLE
Sample Postman Calls

### ISSUE THREAD

**Issue by anish-suki** [virencehealth/apiserver.virencehealth.com#39] opened 2019-07-15 20:49 UTC
Hello,

Does anyone have any sample Postman calls for the FHIR sandbox that they can share? DocumentReference calls would be nice but just about anything to get started is fine. 

Thanks,
Anish

**Comment by SameerSingh1991** [comment] 2019-07-16 09:00
The token generation sample code (https://github.com/virencehealth/apiserver.virencehealth.com/tree/master/token-generation-sample-code) also has a FHIR API call to get the Patient resource. If you replace the Patient resource call with DocumentReference resource call you should get the DocumentReferences.
You can get more details of DocumentReference resource API and supported operations with examples in the API resources tab of dev portal ( goto https://mydata.gehealthcare.com/fhirapidoc > click on Clinical APIs tab > click on DocumentReference in left side menu )

**Comment by SameerSingh1991** [comment] 2019-08-13 12:57
Since the issue is resolved marking it as closed.

**Closed by SameerSingh1991** 2019-08-13 12:57 UTC
