### ISSUE TITLE
Getting refresh token after authentication

### ISSUE THREAD

**Issue by royyin224** [virencehealth/apiserver.virencehealth.com#38] opened 2019-07-10 02:44 UTC
We have completed the authentication flow with API but when the access token is returned to our application, it didn't come with a refresh token, even though we set the scope with "online_access" or "offline_access". We weren't able to find any documentation on it either, is there something else that we are missing?

We are testing our application with work account in Test Sandbox.

**Comment by SameerSingh1991** [comment] 2019-07-17 12:51
Download sample token generation code (https://github.com/virencehealth/apiserver.virencehealth.com/tree/master/token-generation-sample-code) and make the following change

Open file index.html > on line 50 change the scope parameter by appending it with "offline_access%20" in the start . Your new redirect variable will look like this

let redirect = authorizeURL + '?client_id=' + config.clientID + '&state=abc123&redirect_uri=' + config.redirect_url + '&response_type=code%20id_token&response_mode=form_post&aud=https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir' + '&scope=offline_access%20openid%20profile%20user%2FAllergyIntolerance.read%20user%2FPatient.read%20user%2FMedicationStatement.read%20user%2FCondition.read%20user%2FPractitioner.read%20user%2FBinary.read%20user%2FMedicationOrder.read%20user%2FBasicAdvanceDirective.read%20user%2FCoverage.read%20user%2FDocumentReference.read%20user%2FObservation.read%20user%2FFamilyMemberHistory.read%20user%2FProcedure.read%20user%2FAppointment.read%20user%2FSchedule.read%20user%2FSlot.read'

Once this is done you will get the refresh token along with the access token. Open file redirect.html and on line 55 use "tokenRes.refresh_token" to access the refresh token.

**Comment by royyin224** [comment] 2019-07-18 13:52
@SameerSingh1991 Thanks, we got the refresh token, somehow we overlooked it when we tested before with "offline_access", sorry for the trouble

**Comment by SameerSingh1991** [comment] 2019-07-19 03:55
Welcome. Since the issue is resolved marking it as closed.

**Closed by SameerSingh1991** 2019-07-19 03:55 UTC
