### ISSUE TITLE
How to search by Patient ID on Observation Resource

### ISSUE THREAD

**Issue by ellipsecons** [virencehealth/apiserver.virencehealth.com#33] opened 2019-04-10 16:27 UTC
We are having trouble searching the Observation Resource FHIR using patient ID. It works with OBS ID, but not passing the search parameter of patient=. 
Anyone had luck with Observation Resource for retrieving the OBS resources by a patient?

Thanks

**Comment by Torin-Shepard-GE** [comment] 2019-04-10 16:42
Try using search parameter subject

**Comment by ellipsecons** [comment] 2019-04-10 16:46
We tried accessing the resource using the following search parameter, but no luck. 
/fhir/Observation?patient=1864998283176460

It works using the OBSID /fhir/Observation/1870516682762020

Is there anything wrong with how I am using the search parameter? Appreciate your help.

**Comment by Torin-Shepard-GE** [comment] 2019-04-10 16:50
Try Observation?**subject**=1864998283176460

**Comment by ellipsecons** [comment] 2019-04-10 16:52
That worked. Thank you.

**Comment by SameerSingh1991** [comment] 2019-08-13 13:15
Since the issue is resolved marking it as closed.

**Closed by SameerSingh1991** 2019-08-13 13:15 UTC
