### ISSUE TITLE
Centricity FHIR API URL not accessible ????

### ISSUE THREAD

**Issue by v152kuma** [virencehealth/apiserver.virencehealth.com#45] opened 2019-07-31 12:02 UTC
Hi Team,

I would like to get some information about connecting to your FHIR sandbox , specifics are mentioned below :

1). The base url to the FHIR API’s and the conformance API , as per the your documentation and FHIR standards this should be accessible without any security validation .

2). The way to connect to obtain Client_ID and Client_Secret on your web-portal .

I have tried accessing your API’s using the below mentioned links(as per your documentation and sample app on github) , but they are not accessible:
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir 
and
https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir

I have tried registering an App in order to meet the security validation and obtain the secret and id , but that also shows “Registration Unsuccessful” every time , even though we meet all the conditions required for application registration .

Regards,
Vivek

**Comment by SameerSingh1991** [comment] 2019-07-31 12:19
Possible duplicate of #23 

Are you not able to access the below URL https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata

Is your internet access behind a corporate proxy which is blocking port 9443. Can you please let us know what is the exact error that you get ?

**Comment by v152kuma** [comment] 2019-07-31 13:31
Yes I am not able to access this URL , and yeah , I am behind a corporate proxy , because when I am trying to telnet to this URL using 9443 , it shows timed out , is there any work around .
Secondly what about the other issue , when registering an application , it shows registration unsuccessful , the application which we are trying to register is secure with https , its hosted on our corporate cloud as well . Is that also because of proxy ???

**Comment by SameerSingh1991** [comment] 2019-07-31 13:55
Can you try using mobile or open internet for accessing both FHIR server URL as well as the Centricity Developer Portal. Try removing the proxy settings from internet options on your windows laptop.

**Comment by SameerSingh1991** [comment] 2019-10-29 06:44
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.

**Closed by SameerSingh1991** 2019-10-29 06:44 UTC
