### ISSUE TITLE
Getting a 404 error/Not found error when selecting test patient in the Test Sandbox

### ISSUE THREAD

**Issue by cdproctor** [virencehealth/apiserver.virencehealth.com#32] opened 2019-03-12 12:32 UTC
**Describe the bug**
I am able to get to the Access My Data in the test sandbox, but after I sign into either the personal account or work account and select a test patient, I am getting a not found error in the browser. I am using Google Chrome. The link that I am using is: https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://apisandbox.gehealthcare.com:9443/demoAPIServer&aud=https%3A%2F%2Fapisandbox.gehealthcare.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2FwaXNhbmRib3guZ2VoZWFsdGhjYXJlLmNvbTo5NDQzXC9kZW1vQVBJU2VydmVyXC8iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvYXBpc2FuZGJveC5nZWhlYWx0aGNhcmUuY29tOjk0NDNcL2RlbW9hcGlzZXJ2ZXIiLCJodHRwczpcL1wvYXBpc2FuZGJveC5nZWhlYWx0aGNhcmUuY29tOjk0NDNcL2RlbW9hcGlzZXJ2ZXJcLyJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEuMC4wIiwibmF0aXZlX2NsaWVudCI6ZmFsc2UsImh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbVwvb2F1dGgyLmNsYWltc1wvYXBwX2lkIjoiODM5ZjY5ZGUtMDNjYS00YmQ1LWE0YzYtMjJiZTAyMTNkMDcwIiwiZXhwIjoxODY4MDEyMDAxLCJjbGllbnRfbmFtZSI6IlRlc3RTYW5kYm94IiwiaWF0IjoxNTUyMzkyODAxLCJjb250YWN0cyI6WyJjcHJvY3RvckB0cmluZXRtZWRpY2FsLmNvbSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.VRhB9I4r0Pg0DLJgl9YqPfMO5Q0NLSIjy3zLaT6mUImbALCIwTZZj7vDHJMwFV36pNltli3QP-G5r6XKrGMSqt3rsRt8vaRgkjEU0_cDXv_5d0qVNEaFVE3EsgR5weIuzwaJhMwShwsFix1tA1vMj6twgle2tTMMrRJGgYi7bt4

**To Reproduce**
1. Go to https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://apisandbox.gehealthcare.com:9443/demoAPIServer&aud=https%3A%2F%2Fapisandbox.gehealthcare.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2FwaXNhbmRib3guZ2VoZWFsdGhjYXJlLmNvbTo5NDQzXC9kZW1vQVBJU2VydmVyXC8iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvYXBpc2FuZGJveC5nZWhlYWx0aGNhcmUuY29tOjk0NDNcL2RlbW9hcGlzZXJ2ZXIiLCJodHRwczpcL1wvYXBpc2FuZGJveC5nZWhlYWx0aGNhcmUuY29tOjk0NDNcL2RlbW9hcGlzZXJ2ZXJcLyJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEuMC4wIiwibmF0aXZlX2NsaWVudCI6ZmFsc2UsImh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbVwvb2F1dGgyLmNsYWltc1wvYXBwX2lkIjoiODM5ZjY5ZGUtMDNjYS00YmQ1LWE0YzYtMjJiZTAyMTNkMDcwIiwiZXhwIjoxODY4MDEyMDAxLCJjbGllbnRfbmFtZSI6IlRlc3RTYW5kYm94IiwiaWF0IjoxNTUyMzkyODAxLCJjb250YWN0cyI6WyJjcHJvY3RvckB0cmluZXRtZWRpY2FsLmNvbSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.VRhB9I4r0Pg0DLJgl9YqPfMO5Q0NLSIjy3zLaT6mUImbALCIwTZZj7vDHJMwFV36pNltli3QP-G5r6XKrGMSqt3rsRt8vaRgkjEU0_cDXv_5d0qVNEaFVE3EsgR5weIuzwaJhMwShwsFix1tA1vMj6twgle2tTMMrRJGgYi7bt4
2. Click on Personal Account or Work account.
3. Sign in.
4. Select test patient.
5. Error happens.

**Expected behavior**
I expected to be able to finish following the guide so I can get the patient authorization code.

**Screenshots**
![image](https://user-images.githubusercontent.com/48479804/54200170-1b4d8780-44a1-11e9-8da1-1dc5e75aa9e9.png)

**Desktop (please complete the following information, if applicable):**
 - OS: Windows 7 & Windows Server 2012 R2 Datacenter
 - Browser: Chrome and Firefox
 - Version Latest?

**Comment by SameerSingh1991** [comment] 2019-03-12 13:16
When you register an app on Centricity Developer portal (https://mydata.gehealthcare.com) you are required to provide redirect URLs. These redirect URLs are the URLs on which the FHIR server will redirect you with the authorization code after you have successfully authenticated.
 
**From the authorize URL that you have shared I can see that you are using wrong redirect URL.** The redirect URL which you are using is https://apisandbox.gehealthcare.com:9443/demoAPIServer which is FHIR server URL and not your application URL. The redirect URL should ideally be a URL in your application on which you want the FHIR server to send the authorization code using POST method.

You will have to develop a page in your application (like http://domain_name/redirect ) which will collect the authorization code and other parameters posted by the FHIR server and use these for token generation. We have a sample code for generating authorization code and token.Following is the link to it.

https://github.com/GEHealthcare/apiserver.gehealthcare.com/tree/master/token-generation-sample-code

In this application https://localhost:3000/redirect.html is the redirect URL.

**Comment by snehapilgaonkar** [comment] 2019-07-25 22:39
I have a similar issue in getting the patient/provider authorization code through sandbox. I am getting an error 
![error](https://user-images.githubusercontent.com/53319173/61913413-a2584500-af02-11e9-93bd-6004983255b3.jpg)

My url - 
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://CentricitySandBox.qvhsystems.com&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL25leHRnZW4ucXZoc3lzdGVtcy5sb2NhbCIsImdyYW50X3R5cGVzIjpbImF1dGhvcml6YXRpb25fY29kZSJdLCJpc3MiOiJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb20iLCJyZWRpcmVjdF91cmlzIjpbImh0dHBzOlwvXC9jZW50cmljaXR5c2FuZGJveC5xdmhzeXN0ZW1zLmNvbSJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEuMC4wIiwibmF0aXZlX2NsaWVudCI6ZmFsc2UsImh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbVwvb2F1dGgyLmNsYWltc1wvYXBwX2lkIjoiYWEwNDUyNDctYjlhNC00MWU4LWJhYWItZDIzOWMxNmEwM2E2IiwiZXhwIjoxODc5MTgxODE0LCJjbGllbnRfbmFtZSI6IlRBQ0hfcXZoc3lzdGVtIiwiaWF0IjoxNTYzNTYyNjE0LCJjb250YWN0cyI6WyJzbmVoYS5waWxnYW9ua2FyQGluZmluZWRpLm5ldCJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.WKZa-iv-kBj_F-LLcJw-_vG1EXlMOxfET5X-9q7GTBGqyC8RFqqCIC87wFwWP_sJ0s93ZlmTAI9ICciIe_ad0RsFO47QcPyLgKZA9SGA0omhF9XndPGwQ7FixhJ_F5npXwdhjjz7lJocxxIiVoZzaLxQkPLVoWYPAe2SG9Yqh8Q

When I click 'Select Patient', I get the error.
redirect Url - https://CentricitySandbox.qvhsystems.com
I am not able to resolve this issue or debug the reason for error.

Thanks

**Comment by SameerSingh1991** [comment] 2019-07-26 10:58
Hi @snehapilgaonkar ,
The URL which you have given above looks fine. I can see that after we click on select patient the sandbox FHIR server redirects to your application. This redirect is actually a POST request which the FHIR server makes to your redirect URL. From the error it seems that your redirect URL (https://CentricitySandbox.qvhsystems.com) is not accepting POST request to it. Have you handled POST request on the redirect URL ?

Is it possible to run your application on localhost and and use our sample token generation code (https://github.com/virencehealth/apiserver.virencehealth.com/tree/master/token-generation-sample-code).

**Comment by snehapilgaonkar** [comment] 2019-07-31 15:10
Thank you for the reply. My redirect URL didn't have a 'POST'.

**Comment by SameerSingh1991** [comment] 2019-08-01 07:27
Welcome. Since the issue is resolved marking it as closed.

**Closed by SameerSingh1991** 2019-08-01 07:27 UTC

**Comment by snehapilgaonkar** [comment] 2019-08-07 22:19
Hi,

It didn't allow me to create another issue/question, so I am opened this closed issue.

I have some questions regarding getting Patient data and its resources.
Is there any way that we can get Patients list along with their Resources data similar to a CCDA? Would there be any endpoint for that?

I have another concern about accessing the sanbox url : https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir  
When I try to access it, get an error-
![image](https://user-images.githubusercontent.com/53319173/62661607-341a7600-b937-11e9-8789-62ed3a103d5a.png)

I checked with our network administrator and learnt that there is a chance that it blocked the request. Would you possibly know what could be the reason? 

Thank You

**Comment by SameerSingh1991** [comment] 2019-08-08 12:17
No, there is no way by which you can get patients list along with their resources. 
You can do the following steps for your problem statement
1. Use the Patient API (  ) to get the list of patients.
E.g. https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/?given=walter
Here we are searching for patient with given name "walter". For other Patient API search parameters refer this link : https://smartappdocsprod.azureedge.net/patient.html#search

2. After getting patient ID use the $everything operation to get all patient related data 
E.g . https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/1239620410000620/$everything).
Here we are getting all resources of the patient with ID 1239620410000620. In this case 1239620410000620 is ID of walter caldwell pateint.
Alternatively once you get the patient ID you can get the various resources of the patient using the various resources APIs like Medication, AllergyIntolerance, Condition etc. List of supported resources available in Centricity Developer Portal (https://mydata.gehealthcare.com/fhirapidoc).

You shouldn't be accessing https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir . What you should be accessing is https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata this URL gives you the FHIR server metadata. Please let us know if you are not able to access the metadata URL. If port 9443 is blocked in your corporate proxy chances are that you may not be able to access this FHIR server. You can switch to an open network as a work around for this.

**Comment by snehapilgaonkar** [comment] 2019-08-09 14:53
Hi,

Thank you for the detailed answer! That definitely helps.
I have another question about getting patient data. According to our business requirement, when we get patient data, we need to get a range as in we get all patients > (patientid)-- patientid being the last patient we retrieved in the previous transaction. So my question is if there is a way while getting patient's data while specifying the range?

Thank You

**Comment by SameerSingh1991** [comment] 2019-08-13 12:43
If I am understanding this correctly you want a list of patients whose ID is more than or less than the patient ID passed in the parameter. If you try to get the list of patients using the URL request (https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient) you will get 20 patient resources per page and also receive two other URLs in links tag with the name next and previous . It will look something like this 

"link": [
        {
            "relation": "self",
            "url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_format=json"
        },
        {
            "relation": "next",
            "url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_after=1442678386400620&_format=json"
        },
        {
            "relation": "prev",
            "url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_before=1880825352082980&_format=json"
        },
        {
            "relation": "first",
            "url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_after=9999999999999999999&_format=json"
        },
        {
            "relation": "last",
            "url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient?_before=-9999999999999999999&_format=json"
        }
    ],
	
Here if you check the next link it has an _after parameter which supplies the ID of the patient. The request will return the patients list after the given patient ID. Same goes for _before parameter. Does this solve your problem statement ?
