### ISSUE TITLE
Getting the access token using the personal account fails

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#53] opened 2019-10-01 20:52 UTC
Attempts to get the access token POSTing to https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/token fail with status code 500 and body

```
{
    "expires_in": 0,
    "error": "invalid_client",
    "error_description": "An unexpected error has occurred. Please try this operation again later."
}
```

This happens after authorizing using the Personal account (Walter.caldwell@outlook.com), I am able to get the access token using the Work Account

**Comment by KedarGanta** [comment] 2020-01-25 00:44
@michelemottini   Please try using these credentials..

User Name: Walter.caldwell@outlook.com
Password: TestPatient!@!

**Comment by michelemottini** [comment] 2020-02-24 15:50
@KedarGanta that's the credentials I am using - never managed to make them work.

Now it fails even earlier - right after entering the password I get this:

![image](https://user-images.githubusercontent.com/1046280/75167514-79479f00-56f3-11ea-878b-e694d04c582b.png)

**Comment by ychowdhary** [comment] 2020-03-09 12:58
@michelemottini Please try using these Credentials
User Name: athenainterop@aol.com
Password: Virence@123

**Comment by michelemottini** [comment] 2020-03-09 14:14
Tried, but it two factor auth kicks in - so I cannot use it:

![image](https://user-images.githubusercontent.com/1046280/76220944-af564a00-61ee-11ea-845f-5e674380d432.png)

**Comment by nkadmane** [comment] 2020-04-07 11:42
@michelemottini 

Please try using these Credentials to login into AOL account and get the code to complete 2 factor authentication.

User Name: athenainterop@aol.com
Password: Virence@123

**Comment by michelemottini** [comment] 2020-04-07 14:19
That worked, thanks - but I still get this crash after I successfully logged in:

![image](https://user-images.githubusercontent.com/1046280/78680293-4f1ffa00-78b9-11ea-8f6f-d298211d94ef.png)

**Comment by KedarGanta** [comment] 2020-04-07 17:41
@michelemottini  We are not able to repro the issue. would you be able to check the steps to invoke patient workflow listed here https://mydata.athenahealth.com/access-centricity-apis

![image](https://user-images.githubusercontent.com/37341248/78701526-0ae22900-78bc-11ea-8d93-e30bdafc5d48.png)

![image](https://user-images.githubusercontent.com/37341248/78701625-31a05f80-78bc-11ea-91a9-35edc58836f1.png)

**Comment by KedarGanta** [comment] 2020-05-29 23:32
@michelemottini  I would assume that the issue is resolved. It is possible that in your URL you are not sending the right scope.. please make sure you have scope=openid profile...I am closing the issue. If you need help please open another issue

**Closed by KedarGanta** 2020-05-29 23:32 UTC
