### ISSUE TITLE
Sync for Science feedback

### ISSUE THREAD

**Issue by abjonnes** [virencehealth/apiserver.virencehealth.com#27] opened 2019-02-22 15:25 UTC
Hi,

I’m a developer with [Sync for Science](http://syncfor.science). We’ve tested the Centricity sandbox environment with our [test suite](https://tests.demo.syncfor.science) and I’d like to share some feedback with you on your implementation.

- Authorization request (standalone launch)
  - The response code when the `redirect_uri` parameter is missing should not be 200 (although the content of the reply does reflect an error state).
  - Certain special characters in the `state` parameter are being mishandled: provided `state` parameter `` `%2B~!@#$%^&*()-_=+[{]}\;:'",<.>/? `` is returned by the server as `` `%2B~!@#$%^&*()-_=+[{]}\;:' ``.
- Refresh tokens
  - The server should not require the `redirect_uri` parameter when accessing the token endpoint with the `refresh_token` grant type [(reference)](http://hl7.org/fhir/smart-app-launch/#step-5-later-app-uses-a-refresh-token-to-obtain-a-new-access-token).
- FHIR payloads
  - Lab results (Observation resources with `category=laboratory`)
    - The `code` attribute should be bound to LOINC per the Argonaut IG.
  - MedicationStatement
    - Some references present in the resource are not resolvable (`Medication/18685`).
  - DocumentReference
    - The `indexed` attribute is missing but is required by the FHIR spec.
    - Some references present in the resource are not resolvable (`Practitioner/1377099406000720`).
  - Condition
    - The `verificationStatus` attribute is missing but is required by the FHIR spec.
    - The `code` attribute should be bound to SNOMED per the Argonaut IG.
  - Procedure
    - Invalid CPT codes are present (90718 and 90724 have been deleted).

We look forward to your feedback!

Thanks,
Andrew Bjonnes
Sync for Science

**Comment by KedarGanta** [comment] 2019-03-04 16:00
Thanks Andrew for the feedback. We are reviewing the details and will make appropriate changes.

**Comment by SameerSingh1991** [comment] 2019-08-13 12:59
Since the issue is resolved marking it as closed.

**Closed by SameerSingh1991** 2019-08-13 12:59 UTC
